accumulate_grad_batches: 1
batch_size: 128
checkpoints_path: ./checkpoints/tiny_hgr
dataset: tiny_hgr
dataset_path: ../../datasets/tiny_hgr
device: auto
image_backbone_name: convnextv2-b
landmarks_backbone_name: linear
lr: 5.0e-05
max_epochs: 3
name: tiny_hgr_loso_convnextv2-b_linear_h-images_h-landmarks
normalize_landmarks: true
seed: 42
train_image_backbone: false
use_horizontal_image: true
use_horizontal_landmarks: true
use_vertical_image: false
use_vertical_landmarks: false
validation: loso
