accumulate_grad_batches: 1
batch_size: 128
checkpoints_path: ./checkpoints/tiny_hgr
dataset: tiny_hgr
dataset_path: ../../datasets/tiny_hgr
device: auto
image_backbone_name: null
landmarks_backbone_name: mlp
lr: 5.0e-05
max_epochs: 3
name: tiny_hgr_loso_None_mlp_no-images_h-landmarks
normalize_landmarks: true
seed: 42
train_image_backbone: false
use_horizontal_image: false
use_horizontal_landmarks: true
use_vertical_image: false
use_vertical_landmarks: false
validation: loso
